[project]
name = "odoo-addons-oca-stock-logistics-warehouse"
version = "18.0.20241010.0"
dependencies = [
    "odoo-addon-stock_packaging_calculator==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
